name: CI
on: [push]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to nerdhood.de
      uses: appleboy/ssh-action@master
      env:
        USERNAME: ubuntu
        HOST: 54.254.223.66
        SCRIPT: echo $USER
        KEY: ${{ secrets.KEY }}