name: AWS VPS
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USER }}
          KEY: ${{ secrets.KEY }}
          SCRIPT: | 
            rm -rf job-under-280 
            git clone https://github.com/adylanrff/job-under-280 
            cd job-under-280
            echo TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }} >> .env
            echo TWITTER_API_SECRET_KEY=${{ secrets.TWITTER_API_SECRET_KEY }} >> .env
            echo TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }} >> .env
            echo TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} >> .env
            echo MONITORING_TWITTER_ACC=${{ secrets.MONITORING_TWITTER_ACC }} >> .env
            echo DB_URI=${{ secrets.DB_URI }} >> .env
            pip3 install -r requirements.txt
            python3 cron.py