name: AWS VPS
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.KEY }}
          script: rm job-under-280 && git clone https://github.com/adylanrff/job-under-280 