name: AWS VPS
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@v2.0.7
        
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
